name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  runJob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g yarn
      - run: |
          yarn
          yarn build
